# https://docs.influxdata.com/influxdb/v2.1/api/
- name: login
  uri:
    method: POST
    url: '{{ influxdb_v2_task_url }}/api/v2/signin'
    force_basic_auth: yes
    # naming `url_{username,password}` based on
    # https://web.archive.org/web/20211226100248/https://docs.ansible.com/ansible/latest/collections/community/grafana/grafana_datasource_module.html#parameter-url_username
    url_username: '{{ influxdb_v2_task_url_username }}'
    url_password: '{{ influxdb_v2_task_url_password }}'
    status_code: 204
  register: _login
- name: 'retrieve current configuration of task {{ influxdb_v2_task_name | to_json }}'
  uri: # https://docs.influxdata.com/influxdb/v2.0/api/#operation/GetTasks
    method: GET
    url: '{{ influxdb_v2_task_url }}/api/v2/tasks?org={{ influxdb_v2_task_org | urlencode }}&name={{ influxdb_v2_task_name | urlencode }}&limit=2'
    headers: {Cookie: '{{ _login.cookies_string }}'}
    status_code: 200
  register: _tasks
- name: 'verify task name {{ influxdb_v2_task_name | to_json }} is unambiguous'
  assert:
    that: (_tasks.json.tasks | length) <= 1
- name: 'create task {{ influxdb_v2_task_name | to_json }}'
  uri: # https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostTasks
    method: POST
    url: '{{ influxdb_v2_task_url }}/api/v2/tasks'
    headers: {Cookie: '{{ _login.cookies_string }}'}
    body_format: json
    body:
      org: '{{ influxdb_v2_task_org }}'
      flux: &full_flux |
        option task = {
            name: "{{ influxdb_v2_task_name }}",
            every: {{ influxdb_v2_task_every }},
        }

        {{ influxdb_v2_task_flux }}
      status: active
    status_code: 201
  changed_when: true
  when: (_tasks.json.tasks | length) == 0
  register: _create
- name: 'update task {{ influxdb_v2_task_name | to_json }}'
  uri: # https://docs.influxdata.com/influxdb/v2.0/api/#operation/PatchTasksID
    method: PATCH
    url: '{{ influxdb_v2_task_url }}/api/v2/tasks/{{ _tasks.json.tasks[0].id | urlencode }}'
    headers: {Cookie: '{{ _login.cookies_string }}'}
    body_format: json
    body:
      every: '{{ influxdb_v2_task_every }}'
      flux: *full_flux
      status: active
    status_code: 200
  changed_when: true
  when: _create.skipped | default(False) # TODO
  # TODO add diff
